def printFullMenu():
    print("------------------------------------------------------Menu--------------------------------------------------------------")
    print("[V]VEG                                                                        [NV]NON VEG")
    print("                                                     [1]Burger")
    print("[1.1]Veg Cheese Burger                60                                      [1.3]Chicken Cheese Burger           70")
    print("[1.2]Veg Barbecue Burger              60                                      [1.4]Chicken Barbecue Burger         70")
    print('-'*130)
    print("\n")
    print("                                                     [2]Rolls")
    print("[2.1]Aloo Tikki Roll                  80                                      [2.4]Chicken Cheese Roll             100")
    print("[2.2]Paneer Cheese Roll               80                                      [2.5]Double Chicken Roll             100")
    print("[2.3]Paneer Barbecue Roll             80                                      [2.6]Chicken Barbecue                100")
    print("-"*130)
    print("\n")
    print("                                                     [3]Chinese")
    print("[3.1]Paneer Chilly Dry                130                                     [3.4]Chicken Chilly Dry              140")
    print("[3.2]Paneer Chilly Rice/Noodles       140                                     [3.5]Chicken Lolipop Oil Fry         140")
    print("[3.3]Shezwan Rice/Noodles             110                                     [3.6]Chicken Lolipop Masala          150")
    print("                                                                              [3.7]Chicken Triple Rice/Noodles     160")
    print("                                                                              [3.8]Chicken Shezwan Rice/Noodles    140")
    print("                                                                              [3.9]Egg Fried Rice                  130")
    print("-"*130)
    print("\n")
    print("                                                     [4]Momos")
    print("[4.1]Mix Veg Momos Steamed             95                                     [4.5]Chicken Momos Steamed           115")
    print("[4.2]Mix Veg Momos Fried               100                                    [4.6]Chicken Momos Fried             120")
    print("[4.3]Paneer Momos Steamed              105")
    print("[4.4]Paneer Momos Fried                110")
    print("-"*130)
    print("\n")
    print("                                                     [5]Biryani")
    print("[5.1]Paneer Biryani                    120                                    [5.2]Chicken Biryani                 140")
    print("="*130)

def main():
    print("Hello Customer what is your name?")
    customerName = input()
    print("Hello {}, what would you like to order today?".format(customerName))
    print("="*80)
    


main()